-- ==============================================================================
-- PHENMO EVENTS — SUPABASE SEED DATA
-- ==============================================================================
-- Run this script in the Supabase SQL Editor after running schema.sql.
-- It populates all 7 departments, all 538 consolidated inventory assets,
-- default staff accounts, and initial events.
-- ==============================================================================

-- 1. STAFF ACCOUNTS
INSERT INTO public.accounts (id, name, role, email, password)
VALUES
    ('steve', 'Steve', 'Admin', 'steve@phenmoevents.co.ke', '0000'),
    ('mariah', 'Mariah', 'Manager', 'mariah@phenmoevents.co.ke', '0000'),
    ('dave', 'Dave', 'Technician', 'dave@phenmoevents.co.ke', '0000')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, email = EXCLUDED.email, password = EXCLUDED.password;

-- 2. INVENTORY CATEGORIES (7 DEPARTMENTS)
INSERT INTO public.inventory_categories (id, name, sort_order)
VALUES
    ('audio', 'Audio & Sound', 1),
    ('visual', 'Visual & Lighting', 2),
    ('stage', 'Stage & Staging', 3),
    ('rigging', 'Rigging & Stands', 4),
    ('cables', 'Cables & Interconnects', 5),
    ('power', 'Power & Distribution', 6),
    ('hardware', 'Cases & Hardware', 7)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

-- 3. INVENTORY ITEMS (538 CONSOLIDATED ROWS REPRESENTING 776 ASSETS)
INSERT INTO public.inventory_items (id, category_id, name, available, status, notes, model, serial_number, serials, sub_category, condition, location)
VALUES
    ('eq-0033', 'audio', 'BEHRINGER 16-CH MIXER', 1, 'Available', 'Location: In Store', 'QX2442USB XENYX USB', 'S1600401AL3', '[]'::jsonb, 'MIXERS', 'Excellent', 'In Store'),
    ('eq-0034', 'audio', 'BEHRINGER 2-CH MIXER 1', 1, 'Available', 'power adapter got burn | Location: In Store', 'XENYX 802 USB', 'S170834612575', '[]'::jsonb, 'MIXERS', 'Excellent', 'In Store'),
    ('eq-0036', 'audio', 'BEHRINGER QX1202 USB 4-CH Mixer', 2, 'Available', '3 units consolidated: 2 Available, 1 Broken/Faulty (Needs Repair). Location: In Store', 'QX1202 USB', 'S170502531ALR', '["S170502531ALR","S170503532ALR","S170502533ALR"]'::jsonb, 'MIXERS', 'Good', 'In Store'),
    ('eq-0039', 'audio', 'BEHRINGER X32 DIGITAL MIXER 1', 1, 'Available', 'Location: In Store', 'X32', 'S170605408ASF', '[]'::jsonb, 'MIXERS', 'Excellent', 'In Store'),
    ('eq-0020', 'audio', 'ECOXGEAR Portable Speaker', 0, 'Reserved', '3 units consolidated: 2 Reserved, 1 Faulty (burned fuse). Location: Lost in Coast', 'GDI-EXBM901', 'HAI160920052', '["HAI160920052","HAI161936486"]'::jsonb, 'SPEAKERS', 'Faulty', 'Lost in Coast'),
    ('eq-0018', 'audio', 'FBT X-LITE 1000W 12" Loudspeaker', 2, 'Available', '2 units consolidated (FIXED). Location: In Store', '38283 X-Lite 12A', 'C03295P446', '["C03295P446","C03295P371"]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0017', 'audio', 'HK 1000W 12" LOUDSPEAKER', 0, 'Broken', 'tweeter burned | Location: In Store', 'HK PL 112 FA', 'A01-133-20325943', '[]'::jsonb, 'SPEAKERS', 'Faulty', 'In Store'),
    ('eq-0016', 'audio', 'HK 1000W 15" LOUDSPEAKER', 0, 'Broken', 'ICE BURNED | Location: Needs Reapairs', 'HK PL 115 FA', 'A01-1333-20325958', '[]'::jsonb, 'SPEAKERS', 'Faulty', 'Needs Reapairs'),
    ('eq-0026', 'audio', 'HK 12" Stage Monitor', 2, 'Available', '2 units consolidated. Location: In Store', 'HK 12" Stage Monitor', 'A01-1047-20271701', '["A01-1047-20271701","A01-1047-20271702"]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0002', 'audio', 'HK 600W 18" SUB', 1, 'Available', 'Location: In Store', 'PL 118 Sub A', 'A01-1333-20325974', '[]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0014', 'audio', 'HK PR:O 10 XA 600W 10" Monitor', 2, 'Available', '2 units consolidated (FIXED). Location: In Store', 'HK PR:O 10 XA', 'A01-1435-20347977', '["A01-1435-20347977","A01-1426-20345290"]'::jsonb, 'SPEAKERS', 'Good', 'In Store'),
    ('eq-0023', 'audio', 'JBL PARTYBOX 300 Bluetooth Speaker', 0, 'Reserved', '3 units consolidated (3 Reserved). Location: Lost in Coast', 'CMIIT ID: 2018DJ5033', 'TL0699-BJ003815', '["TL0699-BJ003815","TL0699-DJ0042539","TL0699-BJ0038053"]'::jsonb, 'SPEAKERS', 'Excellent', 'Lost in Coast'),
    ('eq-0004', 'audio', 'JBL PRX 618S-XLF Subwoofer', 2, 'Available', '2 units consolidated (FIXED). Location: In Store', 'PRX 618 S-XLF', 'P1090-02633', '["P1090-02633","P1090-04305"]'::jsonb, 'SPEAKERS', 'Good', 'In Store'),
    ('eq-0006', 'audio', 'JBL PRX 635 1500W 15" Loudspeaker', 2, 'Available', '2 units consolidated. Location: In Store', 'PRX 635', 'P109012238', '["P109012238","P1090-12241"]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0008', 'audio', 'JBL SRX835P 2000W 15" Loudspeaker', 2, 'Available', '2 units consolidated. Location: In Store', 'SRX835P', 'P1649-11634', '["P1649-11634","P1649-11648"]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0003', 'audio', 'LD SYSTEM 15" SUB SET', 0, 'Broken', 'ONE HAS AN ISSUE | Location: In Store', 'DAVE 15 G3', 'N\A', '[]'::jsonb, 'SPEAKERS', 'Faulty', 'In Store'),
    ('eq-0065', 'audio', 'MAGIC STAR KARAOKE', 1, 'Available', 'Location: In Store', 'MAESTRA', 'MSE1705MAESD101546', '[]'::jsonb, 'AV', 'Excellent', 'In Store'),
    ('eq-0064', 'audio', 'MEDIACOM KARAOKE', 1, 'Available', 'Location: In Store', 'MCI6200TW', '17010837', '[]'::jsonb, 'AV', 'Excellent', 'In Store'),
    ('eq-0001', 'audio', 'NEXT 2200W 18" SUB', 1, 'Available', 'Location: In Store', 'HFA118s', '200627001', '[]'::jsonb, 'SPEAKERS', 'Excellent', 'In Store'),
    ('eq-0029', 'audio', 'PIONEER DDJ SX DJ Console', 0, 'Reserved', '2 units consolidated (1 Reserved - ADAPTER MISSING, 1 Broken/Faulty - CROSS FADER). Location: Sold', 'DDJ SX', 'MEHN004685DA', '["MEHN004685DA","MHHN008100DA"]'::jsonb, 'DJ GEAR', 'Good', 'Sold'),
    ('eq-0028', 'audio', 'PIONEER DJ CONSOLE 1', 0, 'Reserved', 'Location: Sold', 'DDJ SZ', 'NGMP006687EH', '[]'::jsonb, 'DJ GEAR', 'Excellent', 'Sold'),
    ('eq-0031', 'audio', 'PIONEER DJ CONSOLE 4', 1, 'Available', 'Location: in  store', 'DDJ SR', '', '[]'::jsonb, 'DJ GEAR', 'Excellent', 'in  store'),
    ('eq-0032', 'audio', 'PIONEER DJ MEP 700', 1, 'Available', 'Location: In Store', 'DJM 500 MIXER RACK', 'HIMP000155LW', '[]'::jsonb, 'DJ GEAR', 'Excellent', 'In Store'),
    ('eq-0012', 'audio', 'QSC K12 1000W 12" Loudspeaker', 0, 'Reserved', '2 units consolidated (2 Reserved - Donated to Church; SN: GDF540493, GDF540494 casing worn/vibrates). Location: Donated to Church', 'K12', 'GDF540493', '["GDF540493","GDF540494"]'::jsonb, 'SPEAKERS', 'Good', 'Donated to Church'),
    ('eq-0010', 'audio', 'QSC KW 153 1000W 15" Loudspeaker', 1, 'Available', '2 units consolidated: 1 Available (SN: GCC650293 - knob missing), 1 Faulty (SN: GCC650294). Location: In Store', 'KW153', 'GCC650294', '["GCC650294","GCC650293"]'::jsonb, 'SPEAKERS', 'Good', 'In Store'),
    ('eq-0035', 'audio', 'SAMSON 6-CH MIXER', 0, 'Broken', 'Needs Maintance/Channel feeders static | Location: Lost in Coast', 'MXP144FX', '144X4K1478', '[]'::jsonb, 'MIXERS', 'Faulty', 'Lost in Coast'),
    ('eq-0054', 'audio', 'SHURE BETA 52A DRUM MIC 1', 1, 'Available', 'Location: In Store', 'BETA 52A', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0055', 'audio', 'SHURE BETA 58A WIRED MIC 1', 0, 'Reserved', 'Location: Lost in Coast', 'BETA 58A', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'Lost in Coast'),
    ('eq-0056', 'audio', 'SHURE BETA 87A HAND HOLD MIC 1', 0, 'Reserved', 'Location: Lost in Coast', 'SLX2 BETA 87A', '1KK0846967-01', '[]'::jsonb, 'MICS', 'Excellent', 'Lost in Coast'),
    ('eq-0063', 'audio', 'SHURE HEAD SET MIC 1', 1, 'Available', 'Location: In Store', 'MX153T/0-TQG2119', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0049', 'audio', 'SHURE LAPEL 1', 0, 'Broken', 'we need to buy a new mic | Location: In Store', 'BLX4UK/CVLX-K14', '3PG1804823', '[]'::jsonb, 'MICS', 'Faulty', 'In Store'),
    ('eq-0050', 'audio', 'SHURE LAPEL 2', 1, 'Available', 'Location: In Store', 'BLX4UK/CVLX-K15', '30K2297724', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0062', 'audio', 'SHURE MICROFLEX PODIUM MIC 1', 1, 'Available', 'Location: In Store', 'MX418D/C', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0059', 'audio', 'SHURE PG1 LAPEL 1', 0, 'Reserved', 'Location: Lost in Coast', 'PG1 PG4-M10', '1H11020637-04', '[]'::jsonb, 'MICS', 'Excellent', 'Lost in Coast'),
    ('eq-0041', 'audio', 'SHURE PG58 BLX4-K14 Wireless Microphone', 7, 'Available', '8 units consolidated: 7 Available (SN: 3MF1319349-03 [btn repair], 30G1775072-01, 30H1183527-01, 3PF0856308, 3QH0626899, 3PF0856391 [btn/receiver repair], 3QH0626895), 1 Faulty (SN: 3PK1707915 [missing mic]). Location: In Store', 'PG58 BLX4-K14', '3MF1319349-03', '["3MF1319349-03","30G1775072-01","30H1183527-01","3PF0856308","3QH0626899","3PF0856391","3QH0626895","3PK1707915"]'::jsonb, 'MICS', 'Good', 'In Store'),
    ('eq-0060', 'audio', 'SHURE PG58 MIC 1', 0, 'Reserved', 'NO BATTERY | Location: Lost in Coast', 'PG58 PG4-M7', '1KB2864511-O5', '[]'::jsonb, 'MICS', 'Excellent', 'Lost in Coast'),
    ('eq-0057', 'audio', 'SHURE PG81', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0051', 'audio', 'SHURE SM57 Dynamic Drum Mic Kit', 3, 'Available', '3 units consolidated. Location: In Store', 'SM57', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0058', 'audio', 'SHURE SM58 WIRED MIC 1', 0, 'Reserved', 'Location: Lost in Coast', 'SM58', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'Lost in Coast'),
    ('eq-0061', 'audio', 'SHURE SV100 WIRED MIC 1', 1, 'Available', 'Location: In Store', 'SV100', 'N\A', '[]'::jsonb, 'MICS', 'Excellent', 'In Store'),
    ('eq-0040', 'audio', 'SOUND CRAFT 8-C MIXER', 0, 'Reserved', 'Location: Lost in Coast', 'EFX 8', 'RWS 75830199888', '[]'::jsonb, 'MIXERS', 'Excellent', 'Lost in Coast'),
    ('eq-0282', 'cables', '10M HDMI CABLE 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'HDMI CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0283', 'cables', '10M HDMI CABLE 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'HDMI CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0235', 'cables', '10M XLR CABLE 1', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the  Store'),
    ('eq-0238', 'cables', '10M XLR CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0236', 'cables', '10M XLR CABLE 2', 1, 'Available', 'Location: in the Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'in the Store'),
    ('eq-0239', 'cables', '10M XLR CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0237', 'cables', '10M XLR CABLE 3', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the  Store'),
    ('eq-0240', 'cables', '10M XLR CABLE 3', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0234', 'cables', '10M XLR CABLE 8', 0, 'Broken', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Faulty', 'In  Store'),
    ('eq-0248', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0257', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 10', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0249', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0250', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0251', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0252', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0253', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0254', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0255', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0256', 'cables', '10M-1/4" TRS JACK TO XLR CABLE 9', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0426', 'cables', '10M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0427', 'cables', '10M-16A EXTENDER 2', 0, 'Broken', 'The IDN heads were used to make another cable (IND-socket) | Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Faulty', 'In Store'),
    ('eq-0428', 'cables', '10M-16A EXTENDER 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0429', 'cables', '10M-16A EXTENDER 4', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the  Store'),
    ('eq-0271', 'cables', '15M SPEAKON CABLE 1', 1, 'Available', 'Location: in the  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'in the  Store'),
    ('eq-0272', 'cables', '15M SPEAKON CABLE 2', 1, 'Available', 'Location: in the Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'in the Store'),
    ('eq-0273', 'cables', '15M SPEAKON CABLE 3', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0269', 'cables', '15M- 1\4" JACK TO JACK CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0430', 'cables', '15M-16A EXTENDER 1', 0, 'Reserved', 'Location: missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'missing from Store'),
    ('eq-0431', 'cables', '15M-16A EXTENDER 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0458', 'cables', '16A POWER ICE 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0459', 'cables', '16A POWER ICE 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0460', 'cables', '16A POWER ICE 3', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0461', 'cables', '16A POWER ICE 4', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0462', 'cables', '16A POWER ICE 5', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0463', 'cables', '16A POWER ICE 6', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0464', 'cables', '16A POWER ICE 7', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0465', 'cables', '16A POWER ICE 8', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, '16A POWER CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0241', 'cables', '20M XLR CABLE 1', 1, 'Available', 'Location: In the Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the Store'),
    ('eq-0242', 'cables', '20M XLR CABLE 2', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the store'),
    ('eq-0243', 'cables', '20M XLR CABLE 3', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the  Store'),
    ('eq-0270', 'cables', '20M- 1\4" JACK TO JACK CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0432', 'cables', '20M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0433', 'cables', '20M-16A EXTENDER 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0434', 'cables', '22M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0280', 'cables', '25M SNAKE CABLE', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0244', 'cables', '25M XLR CABLE 1', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the  Store'),
    ('eq-0435', 'cables', '25M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0436', 'cables', '25M-16A EXTENDER 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0437', 'cables', '25M-16A EXTENDER 3', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0276', 'cables', '2M MIC CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0277', 'cables', '2M MIC CABLE 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0245', 'cables', '30M XLR CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0274', 'cables', '3M MIC CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0275', 'cables', '3M MIC CABLE 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0258', 'cables', '3M- 1\4" JACK TO JACK CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0259', 'cables', '3M- 1\4" JACK TO JACK CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0260', 'cables', '3M- 1\4" JACK TO JACK CABLE 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0261', 'cables', '3M- 1\4" JACK TO JACK CABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0281', 'cables', '50M  SNAKE CABLE', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0246', 'cables', '50M XLR CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0247', 'cables', '50M XLR CABLE 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0438', 'cables', '50M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0278', 'cables', '5M MIC CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0279', 'cables', '5M MIC CABLE 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0216', 'cables', '5M XLR CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0225', 'cables', '5M XLR CABLE 10', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0226', 'cables', '5M XLR CABLE 11', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0227', 'cables', '5M XLR CABLE 12', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0228', 'cables', '5M XLR CABLE 13', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0229', 'cables', '5M XLR CABLE 14', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0230', 'cables', '5M XLR CABLE 15', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0231', 'cables', '5M XLR CABLE 16', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0232', 'cables', '5M XLR CABLE 17', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0233', 'cables', '5M XLR CABLE 18', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0217', 'cables', '5M XLR CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0218', 'cables', '5M XLR CABLE 3', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0219', 'cables', '5M XLR CABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0220', 'cables', '5M XLR CABLE 5', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0221', 'cables', '5M XLR CABLE 6', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0222', 'cables', '5M XLR CABLE 7', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0223', 'cables', '5M XLR CABLE 8', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0224', 'cables', '5M XLR CABLE 9', 1, 'Available', 'Location: In  Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In  Store'),
    ('eq-0266', 'cables', '5M- 1\4" JACK TO JACK CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0267', 'cables', '5M- 1\4" JACK TO JACK CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0262', 'cables', '5M- 1\4" JACK TO JACK CABLE 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0263', 'cables', '5M- 1\4" JACK TO JACK CABLE 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In Store'),
    ('eq-0264', 'cables', '5M- 1\4" JACK TO JACK CABLE 7', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the store'),
    ('eq-0265', 'cables', '5M- 1\4" JACK TO JACK CABLE 8', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'In the store'),
    ('eq-0419', 'cables', '5M-16A EXTENDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0420', 'cables', '5M-16A EXTENDER 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0421', 'cables', '5M-16A EXTENDER 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0422', 'cables', '5M-16A EXTENDER 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0423', 'cables', '5M-16A EXTENDER 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0424', 'cables', '5M-16A EXTENDER 6', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0425', 'cables', '5M-16A EXTENDER 7', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0268', 'cables', '6M- 1\4" JACK TO JACK CABLE 1', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'XLR CABLES', 'Excellent', 'Missing from Store'),
    ('eq-0385', 'cables', 'DANCE FLOOR POWER CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0394', 'cables', 'DANCE FLOOR POWER CABLE 10', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0386', 'cables', 'DANCE FLOOR POWER CABLE 2', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0387', 'cables', 'DANCE FLOOR POWER CABLE 3', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0388', 'cables', 'DANCE FLOOR POWER CABLE 4', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0389', 'cables', 'DANCE FLOOR POWER CABLE 5', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0390', 'cables', 'DANCE FLOOR POWER CABLE 5', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0391', 'cables', 'DANCE FLOOR POWER CABLE 7', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0392', 'cables', 'DANCE FLOOR POWER CABLE 8', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0393', 'cables', 'DANCE FLOOR POWER CABLE 9', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'Missing from Store'),
    ('eq-0776', 'cables', 'ETHERNET CABLES', 1, 'Available', 'Location: in the store', 'N/A', 'N/A', '[]'::jsonb, 'LED SCREENS', 'Excellent', 'in the store'),
    ('eq-0400', 'cables', 'LOOP CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0401', 'cables', 'LOOP CABLE 2', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0402', 'cables', 'LOOP CABLE 3', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0403', 'cables', 'LOOP CABLE 4', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0404', 'cables', 'LOOP CABLE 5', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0405', 'cables', 'LOOP CABLE 6', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0357', 'cables', 'SPEAKER POWER CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0366', 'cables', 'SPEAKER POWER CABLE 10', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0367', 'cables', 'SPEAKER POWER CABLE 11', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0368', 'cables', 'SPEAKER POWER CABLE 12', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0369', 'cables', 'SPEAKER POWER CABLE 13', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0370', 'cables', 'SPEAKER POWER CABLE 14', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0371', 'cables', 'SPEAKER POWER CABLE 15', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0372', 'cables', 'SPEAKER POWER CABLE 16', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0373', 'cables', 'SPEAKER POWER CABLE 17', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0374', 'cables', 'SPEAKER POWER CABLE 18', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0375', 'cables', 'SPEAKER POWER CABLE 19', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0358', 'cables', 'SPEAKER POWER CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0376', 'cables', 'SPEAKER POWER CABLE 20', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0377', 'cables', 'SPEAKER POWER CABLE 21', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In the store'),
    ('eq-0378', 'cables', 'SPEAKER POWER CABLE 22', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0379', 'cables', 'SPEAKER POWER CABLE 23', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0380', 'cables', 'SPEAKER POWER CABLE 24', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0381', 'cables', 'SPEAKER POWER CABLE 25', 0, 'Reserved', 'Location: missing from the store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'missing from the store'),
    ('eq-0382', 'cables', 'SPEAKER POWER CABLE 26', 0, 'Reserved', 'Location: missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'missing from Store'),
    ('eq-0383', 'cables', 'SPEAKER POWER CABLE 27', 0, 'Reserved', 'Location: missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'missing from Store'),
    ('eq-0384', 'cables', 'SPEAKER POWER CABLE 28', 0, 'Reserved', 'Location: missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'missing from Store'),
    ('eq-0359', 'cables', 'SPEAKER POWER CABLE 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0360', 'cables', 'SPEAKER POWER CABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0361', 'cables', 'SPEAKER POWER CABLE 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0362', 'cables', 'SPEAKER POWER CABLE 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0363', 'cables', 'SPEAKER POWER CABLE 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0364', 'cables', 'SPEAKER POWER CABLE 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0365', 'cables', 'SPEAKER POWER CABLE 9', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0395', 'cables', 'SPEAKON  POWER CABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0396', 'cables', 'SPEAKON  POWER CABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0397', 'cables', 'SPEAKON  POWER CABLE 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0398', 'cables', 'SPEAKON  POWER CABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0399', 'cables', 'SPEAKON  POWER CABLE 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A POWER CABLE', 'Excellent', 'In Store'),
    ('eq-0215', 'hardware', '1M DANCE FLOOR SKIRTING 8PCS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'DANCEFLOOR SKIRTING', 'Fair', 'Lost in Coast'),
    ('eq-0214', 'hardware', '2M DANCE FLOOR SKIRTING 14PCS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'DANCEFLOOR SKIRTING', 'Fair', 'Lost in Coast'),
    ('eq-0726', 'hardware', 'ALUMINIUM TROLLEY 1', 0, 'Broken', 'LOST IN MARINA | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'ALL PURPOSE TROLLEY', 'Faulty', 'Lost in Coast'),
    ('eq-0727', 'hardware', 'ALUMINIUM TROLLEY 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'ALL PURPOSE TROLLEY', 'Excellent', 'Lost in Coast'),
    ('eq-0748', 'hardware', 'BROTHER LABLE PRINTER 1', 1, 'Available', 'Location: In Store', 'PT-E110VP', '', '[]'::jsonb, 'LABLE PRINTER', 'Excellent', 'In Store'),
    ('eq-0745', 'hardware', 'CABLE TESTER 1', 1, 'Available', 'Location: In Store', 'MJG JACOBS CT-04C', 'N\A', '[]'::jsonb, 'REPAIR KIT', 'Excellent', 'In Store'),
    ('eq-0747', 'hardware', 'CANON WIRELSS PRINTER 1', 0, 'Broken', 'MISSING PRINTER CARTRIGE | Location: Lost in Coast', 'PIXMA MG3640', 'KJXE31083', '[]'::jsonb, 'PRINTER', 'Faulty', 'Lost in Coast'),
    ('eq-0758', 'hardware', 'EVERPORATIVE AIR COOLER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'FAN', 'Excellent', 'In Store'),
    ('eq-0716', 'hardware', 'FLIGHT CASE', 1, 'Available', 'Location: In Store', '', '', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0717', 'hardware', 'FLIGHT CASE', 1, 'Available', 'Location: In Store', '', '', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0718', 'hardware', 'FLIGHT CASE', 1, 'Available', 'Location: In Store', '', '', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0706', 'hardware', 'FLIGHT CASE  FOR BEHRINGER 16C MIXR 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0714', 'hardware', 'FLIGHT CASE  FOR CYCLOPSE', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0713', 'hardware', 'FLIGHT CASE FOR ADJ MOVING HEAD 2', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0712', 'hardware', 'FLIGHT CASE FOR ADJ MOVING HEAD I', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0715', 'hardware', 'FLIGHT CASE FOR ANTARL SMOKE MACHINE 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0709', 'hardware', 'FLIGHT CASE FOR MEP 700 DJ CONSOLE 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0703', 'hardware', 'FLIGHT CASE FOR POWER CABLE 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0704', 'hardware', 'FLIGHT CASE FOR POWER CABLE 2', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0710', 'hardware', 'FLIGHT CASE FOR SHURE MIC 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0711', 'hardware', 'FLIGHT CASE FOR SHURE MIC RECIVER 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0708', 'hardware', 'FLIGHT CASE FOR STAGE ITEMS 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0705', 'hardware', 'FLIGT CASE FOR BEHRINGER X32  MIXER 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0707', 'hardware', 'FLIGT CASE FOR SOUND CRAFT MIXER 8-CH MIXER 1', 1, 'Available', 'Location: In Store', '', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0746', 'hardware', 'GLUE GUN 1', 1, 'Available', 'Location: In Store', '0-GR25', 'N\A', '[]'::jsonb, 'REPAIR KIT', 'Excellent', 'In Store'),
    ('eq-0744', 'hardware', 'HEAT GUN 1', 1, 'Available', 'Location: In Store', 'PPT-HG-002', '32160627088', '[]'::jsonb, 'REPAIR KIT', 'Excellent', 'In Store'),
    ('eq-0740', 'hardware', 'HEAVY DUTY CABLE RAMP 1', 0, 'Reserved', 'LOST IN ABU DHABI | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0741', 'hardware', 'HEAVY DUTY CABLE RAMP 2', 0, 'Reserved', 'LOST IN ABU DHABI | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0742', 'hardware', 'HEAVY DUTY CABLE RAMP 3', 0, 'Reserved', 'LOST IN ABU DHABI | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0743', 'hardware', 'HEAVY DUTY CABLE RAMP 4', 0, 'Reserved', 'LOST IN ABU DHABI | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0773', 'hardware', 'HP LAPTOP', 1, 'Available', 'Location: In store', 'N/A', 'N/A', '[]'::jsonb, 'LAPTOP', 'Excellent', 'In store'),
    ('eq-0733', 'hardware', 'LIGHT DUTY CABLE RAMP 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'In Store'),
    ('eq-0734', 'hardware', 'LIGHT DUTY CABLE RAMP 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'In Store'),
    ('eq-0735', 'hardware', 'LIGHT DUTY CABLE RAMP 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'In Store'),
    ('eq-0736', 'hardware', 'LIGHT DUTY CABLE RAMP 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'In Store'),
    ('eq-0737', 'hardware', 'LIGHT DUTY CABLE RAMP 5', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0738', 'hardware', 'LIGHT DUTY CABLE RAMP 6', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0739', 'hardware', 'LIGHT DUTY CABLE RAMP 7', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'CABLE RAMP', 'Excellent', 'Lost in Coast'),
    ('eq-0728', 'hardware', 'METALLIC DANCE FLOOR TROLLEY 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'DANCE FLOOR TROLLY', 'Excellent', 'In Store'),
    ('eq-0729', 'hardware', 'METALLIC DANCE FLOOR TROLLEY 2', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'DANCE FLOOR TROLLY', 'Excellent', 'Missing from Store'),
    ('eq-0730', 'hardware', 'METALLIC STAGE TROLLEY 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'STAGE TROLLEY', 'Excellent', 'In Store'),
    ('eq-0756', 'hardware', 'PHENMO BANNER 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'BANNER', 'Excellent', 'Lost in Coast'),
    ('eq-0770', 'hardware', 'PHENMO BANNER 1', 1, 'Available', 'Location: in the store', 'N/A', 'N/A', '[]'::jsonb, 'BANNER', 'Excellent', 'in the store'),
    ('eq-0757', 'hardware', 'PHENMO BANNER 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'BANNER', 'Excellent', 'Lost in Coast'),
    ('eq-0771', 'hardware', 'PHENMO BANNER 2', 1, 'Available', 'Location: In the store', 'N/A', 'N/A', '[]'::jsonb, 'BANNER', 'Excellent', 'In the store'),
    ('eq-0760', 'hardware', 'PLASTIC PORTABLE TABLE 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'PLASTIC TABLE', 'Fair', 'Lost in Coast'),
    ('eq-0753', 'hardware', 'SAFETY BOOTS 4PRS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'BOOTS', 'Excellent', 'Lost in Coast'),
    ('eq-0754', 'hardware', 'SAFETY HARNESS 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'HARNESS', 'Excellent', 'Lost in Coast'),
    ('eq-0755', 'hardware', 'SAFETY HELMENT 6PCS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'HELMENT', 'Excellent', 'Lost in Coast'),
    ('eq-0752', 'hardware', 'SAFETY JACKETS 11PCS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'JACKETS', 'Excellent', 'Lost in Coast'),
    ('eq-0769', 'hardware', 'SOLDERING GUN', 1, 'Available', 'Location: in the store', 'N/A', 'N/A', '[]'::jsonb, 'SOLDERING', 'Excellent', 'in the store'),
    ('eq-0761', 'hardware', 'TENT COVER 25m', 0, 'Reserved', 'Location: Lost in Coast', '', '', '[]'::jsonb, '', 'Good', 'Lost in Coast'),
    ('eq-0731', 'hardware', 'TOOL BOX 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'TOOL BOX', 'Excellent', 'In Store'),
    ('eq-0732', 'hardware', 'TOOL BOX2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'TOOL BOX', 'Excellent', 'In Store'),
    ('eq-0719', 'hardware', 'WATER PROOF CASE FOR MIC 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0720', 'hardware', 'WATER PROOF CASE FOR MIC 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0721', 'hardware', 'WATER PROOF CASE FOR MIC 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'CASE', 'Excellent', 'In Store'),
    ('eq-0759', 'hardware', 'WHITE BOARD 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'WHITE BOARD', 'Excellent', 'Lost in Coast'),
    ('eq-0762', 'hardware', 'WOODEN PORTABLE TABLE 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'WOODEN TABLE', 'Fair', 'Lost in Coast'),
    ('eq-0722', 'hardware', 'WOODEN TROLLEY 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'WOODEN TROLLEY', 'Excellent', 'In Store'),
    ('eq-0723', 'hardware', 'WOODEN TROLLEY 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'WOODEN TROLLEY', 'Excellent', 'In Store'),
    ('eq-0724', 'hardware', 'WOODEN TROLLEY 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'WOODEN TROLLEY', 'Excellent', 'In Store'),
    ('eq-0725', 'hardware', 'WOODEN TROLLEY 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'WOODEN TROLLEY', 'Excellent', 'In Store'),
    ('eq-0466', 'power', '13A POWER EXT 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Excellent', 'In Store'),
    ('eq-0475', 'power', '13A POWER EXT 10', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0476', 'power', '13A POWER EXT 11', 0, 'Broken', 'Location: missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Faulty', 'missing from Store'),
    ('eq-0477', 'power', '13A POWER EXT 12', 0, 'Broken', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Faulty', 'In Store'),
    ('eq-0478', 'power', '13A POWER EXT 13', 0, 'Broken', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Faulty', 'In Store'),
    ('eq-0467', 'power', '13A POWER EXT 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Excellent', 'In Store'),
    ('eq-0468', 'power', '13A POWER EXT 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Excellent', 'In Store'),
    ('eq-0469', 'power', '13A POWER EXT 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0470', 'power', '13A POWER EXT 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0471', 'power', '13A POWER EXT 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0472', 'power', '13A POWER EXT 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0473', 'power', '13A POWER EXT 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0474', 'power', '13A POWER EXT 9', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A', 'Good', 'In Store'),
    ('eq-0448', 'power', '13A-16A PLUG CONVERTER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0457', 'power', '13A-16A PLUG CONVERTER 10', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'Missing from Store'),
    ('eq-0449', 'power', '13A-16A PLUG CONVERTER 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0450', 'power', '13A-16A PLUG CONVERTER 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0451', 'power', '13A-16A PLUG CONVERTER 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0452', 'power', '13A-16A PLUG CONVERTER 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0453', 'power', '13A-16A PLUG CONVERTER 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'In Store'),
    ('eq-0454', 'power', '13A-16A PLUG CONVERTER 7', 0, 'Reserved', 'Location: missing from the store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'missing from the store'),
    ('eq-0455', 'power', '13A-16A PLUG CONVERTER 8', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'Missing from Store'),
    ('eq-0456', 'power', '13A-16A PLUG CONVERTER 9', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '13A-16A', 'Excellent', 'Missing from Store'),
    ('eq-0413', 'power', '16 APOWER EXT 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0406', 'power', '16A POWER EXT 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0415', 'power', '16A POWER EXT 10', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0416', 'power', '16A POWER EXT 11', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0417', 'power', '16A POWER EXT 12', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0418', 'power', '16A POWER EXT 13', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0407', 'power', '16A POWER EXT 2', 1, 'Available', 'Location: In the Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the Store'),
    ('eq-0408', 'power', '16A POWER EXT 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0409', 'power', '16A POWER EXT 4', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the  Store'),
    ('eq-0410', 'power', '16A POWER EXT 5', 1, 'Available', 'Location: In the Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the Store'),
    ('eq-0411', 'power', '16A POWER EXT 6', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the  Store'),
    ('eq-0412', 'power', '16A POWER EXT 7', 1, 'Available', 'Location: In the  Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In the  Store'),
    ('eq-0414', 'power', '16A POWER EXT 9', 1, 'Available', 'Location: In The Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In The Store'),
    ('eq-0439', 'power', '16A-3WAY SPLITTER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0440', 'power', '16A-3WAY SPLITTER 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0441', 'power', '16A-3WAY SPLITTER 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0442', 'power', '16A-3WAY SPLITTER 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0443', 'power', '16A-3WAY SPLITTER 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0444', 'power', '16A-3WAY SPLITTER 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'In Store'),
    ('eq-0445', 'power', '16A-3WAY SPLITTER 7', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0446', 'power', '16A-3WAY SPLITTER 8', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, '16A', 'Excellent', 'Missing from Store'),
    ('eq-0479', 'power', 'ADJ WIRELESS 16A POWER DISTR0 1', 0, 'Reserved', 'Location: Lost in Coast', 'WITECH8', '45083327-A00', '[]'::jsonb, '16A', 'Excellent', 'Lost in Coast'),
    ('eq-0480', 'power', 'ADJ WIRELESS 16A POWER DISTR0 2**', 0, 'Reserved', 'Location: Lost in Coast', 'WITECH8', '45083291-A00', '[]'::jsonb, '16A', 'Excellent', 'Lost in Coast'),
    ('eq-0481', 'power', 'INVERTER GENERATOR 1', 0, 'Reserved', 'Location: Lost in Coast', 'SC2300i-H', '1904170004', '[]'::jsonb, 'GENERATOR POWER', 'Excellent', 'Lost in Coast'),
    ('eq-0447', 'power', 'POWER DISTRO 32A-6(16A) 1', 1, 'Available', 'Location: In Store', 'SDC360', '1003150312AE00000865', '[]'::jsonb, '32A', 'Excellent', 'In Store'),
    ('eq-0774', 'power', 'RCCB', 0, 'Broken', 'Got burnt | Location: in the store', 'N/A', 'N/A', '[]'::jsonb, 'RCCB', 'Faulty', 'in the store'),
    ('eq-0765', 'power', 'Voltage Regulator', 1, 'Available', 'Location: In the store', 'N/A', 'N/A', '[]'::jsonb, 'POWER', 'Excellent', 'In the store'),
    ('eq-0766', 'power', 'Voltage Regulator', 1, 'Available', 'Location: In the store', 'N/A', 'N/A', '[]'::jsonb, 'POWER', 'Excellent', 'In the store'),
    ('eq-0767', 'power', 'Voltage Regulator', 1, 'Available', 'Location: In the store', 'N/A', 'N/A', '[]'::jsonb, 'POWER', 'Excellent', 'In the store'),
    ('eq-0764', 'power', 'Voltage regulator 1', 1, 'Available', 'Location: In the store', 'N/A', 'N/A', '[]'::jsonb, 'POWER', 'Excellent', 'In the store'),
    ('eq-0330', 'rigging', '1M ALLUMINIUM TRUSS 1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0339', 'rigging', '1M ALLUMINIUM TRUSS 10', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0331', 'rigging', '1M ALLUMINIUM TRUSS 2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0332', 'rigging', '1M ALLUMINIUM TRUSS 3', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0333', 'rigging', '1M ALLUMINIUM TRUSS 4', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0334', 'rigging', '1M ALLUMINIUM TRUSS 5', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0335', 'rigging', '1M ALLUMINIUM TRUSS 6', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0336', 'rigging', '1M ALLUMINIUM TRUSS 7', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0337', 'rigging', '1M ALLUMINIUM TRUSS 8', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0338', 'rigging', '1M ALLUMINIUM TRUSS 9', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0344', 'rigging', '23KG  TRUSS BASE PLATE 1', 1, 'Available', 'Location: In Store', 'N\A', 'S58010318', '[]'::jsonb, 'BASE PLATE', 'Excellent', 'In Store'),
    ('eq-0345', 'rigging', '23KG  TRUSS BASE PLATE 2', 1, 'Available', 'Location: In Store', 'N\A', 'S57010318', '[]'::jsonb, 'BASE PLATE', 'Excellent', 'In Store'),
    ('eq-0327', 'rigging', '2M ALLUMINIUM TRUSS 1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0328', 'rigging', '2M ALLUMINIUM TRUSS 2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0329', 'rigging', '2M ALLUMINIUM TRUSS 3', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0750', 'rigging', '2M MULTIPURPOSE LADDER 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'MULTIPURPOSE', 'Excellent', 'Lost in Coast'),
    ('eq-0321', 'rigging', '3M ALLUMINIUM TRUSS  1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0322', 'rigging', '3M ALLUMINIUM TRUSS  2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0323', 'rigging', '3M ALLUMINIUM TRUSS  3', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0324', 'rigging', '3M ALLUMINIUM TRUSS  4', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0325', 'rigging', '3M ALLUMINIUM TRUSS  5', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0326', 'rigging', '3M ALLUMINIUM TRUSS  6', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0749', 'rigging', '3M WALL LADDER 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'WALL LADDER', 'Excellent', 'In Store'),
    ('eq-0346', 'rigging', '41KG TRUSS BASE PLATE 1', 1, 'Available', 'Location: In Store', 'N\A', 'M55010318', '[]'::jsonb, 'BASE PLATE', 'Excellent', 'In Store'),
    ('eq-0347', 'rigging', '41KG TRUSS BASE PLATE 2', 1, 'Available', 'Location: In Store', 'N\A', 'M52010318', '[]'::jsonb, 'BASE PLATE', 'Excellent', 'In Store'),
    ('eq-0348', 'rigging', 'EUROTRUSS LIFTER 1', 1, 'Available', 'Location: In Store', 'TL 530', 'N/A', '[]'::jsonb, 'LIFTER', 'Excellent', 'In Store'),
    ('eq-0349', 'rigging', 'EUROTRUSS LIFTER 2', 1, 'Available', 'Location: In Store', 'TL 530', 'N/A', '[]'::jsonb, 'LIFTER', 'Excellent', 'In Store'),
    ('eq-0353', 'rigging', 'HERCULES LIGHTSTAND 1', 1, 'Available', 'Location: In Store', 'HC-SS710B', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0354', 'rigging', 'HERCULES LIGHTSTAND 2', 1, 'Available', 'Location: In Store', 'HC-SS710B', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0355', 'rigging', 'HERCULES LIGHTSTAND 3', 1, 'Available', 'Location: In Store', 'HC-SS710B', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0356', 'rigging', 'HERCULES LIGHTSTAND 4', 1, 'Available', 'Location: In Store', 'HC-SS710B', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0314', 'rigging', 'HERCULES MIC STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Good', 'In Store'),
    ('eq-0315', 'rigging', 'HERCULES MIC STAND 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Good', 'In Store'),
    ('eq-0350', 'rigging', 'JACOB LIFTER/LIGHT STAND 1', 1, 'Available', 'needs service | Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0351', 'rigging', 'JACOB LIFTER/LIGHT STAND 2', 1, 'Available', 'needs service | Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0352', 'rigging', 'JACOB LIFTER/LIGHT STAND 3', 1, 'Available', 'needs service | Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'LIGHT STAND', 'Excellent', 'In Store'),
    ('eq-0311', 'rigging', 'JACOBS MIC STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Fair', 'In Store'),
    ('eq-0312', 'rigging', 'JACOBS MIC STAND 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Fair', 'In Store'),
    ('eq-0313', 'rigging', 'JACOBS MIC STAND 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Fair', 'In Store'),
    ('eq-0310', 'rigging', 'JACOBS MINI BOOM MIC STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0317', 'rigging', 'JACOBS MUSIC STAND', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N/A', '[]'::jsonb, 'MUSIC STAND', 'Good', 'Lost in Coast'),
    ('eq-0290', 'rigging', 'JACOBS SPEAKER STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0291', 'rigging', 'JACOBS SPEAKER STAND 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0292', 'rigging', 'JACOBS SPEAKER STAND 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0293', 'rigging', 'JACOBS SPEAKER STAND 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0294', 'rigging', 'JACOBS SPEAKER STAND 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0295', 'rigging', 'JACOBS SPEAKER STAND 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Fair', 'In Store'),
    ('eq-0296', 'rigging', 'JACOBS SPEAKER STAND 7', 0, 'Broken', 'Missing Screw lock stopper | Location: Donated to Church', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Faulty', 'Donated to Church'),
    ('eq-0297', 'rigging', 'JACOBS SPEAKER STAND 8', 0, 'Broken', 'Missing Screw lock stopper | Location: Donated to Church', 'N\A', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Faulty', 'Donated to Church'),
    ('eq-0288', 'rigging', 'JBL SPEAKER STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'SPEAKER STAND', 'Excellent', 'In Store'),
    ('eq-0289', 'rigging', 'JBL SPEAKER STAND 2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'SPEAKER STAND', 'Excellent', 'In Store'),
    ('eq-0319', 'rigging', 'KEYBOARD STAND', 1, 'Available', 'Location: In the store', 'N\A', 'N/A', '[]'::jsonb, 'KEY BOARD', 'Excellent', 'In the store'),
    ('eq-0298', 'rigging', 'ONSTAGE SPEAKER STAND', 0, 'Broken', 'Missing Screw lock stopper | Location: In Store', 'SPS 023', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Faulty', 'In Store'),
    ('eq-0299', 'rigging', 'ONSTAGE SPEAKER STAND', 0, 'Broken', 'Missing Screw lock stopper | Location: In Store', 'SPS 024', 'N\A', '[]'::jsonb, 'SPEAKER STAND', 'Faulty', 'In Store'),
    ('eq-0301', 'rigging', 'PROJECTOR BASE STAND MOUNT 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'PROJECTOR BASE STAND', 'Good', 'Lost in Coast'),
    ('eq-0302', 'rigging', 'PROJECTOR SCREEN STAND 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'SCREEN STAND', 'Good', 'Lost in Coast'),
    ('eq-0300', 'rigging', 'PROJECTOR STAND 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'PROJECTOR STAND', 'Good', 'Lost in Coast'),
    ('eq-0303', 'rigging', 'SAMSON MIC STAND 1', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0304', 'rigging', 'SAMSON MIC STAND 2', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0305', 'rigging', 'SAMSON MIC STAND 3', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0306', 'rigging', 'SAMSON MIC STAND 4', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0307', 'rigging', 'SAMSON MIC STAND 5', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0308', 'rigging', 'SAMSON MIC STAND 6', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Excellent', 'In Store'),
    ('eq-0309', 'rigging', 'SAMSON MIC STAND 7', 1, 'Available', 'Location: In Store', 'BL3VP', 'N\A', '[]'::jsonb, 'MIC STAND', 'Fair', 'In Store'),
    ('eq-0316', 'rigging', 'STANTON UBERSTAND LAPTOP STAND 1', 0, 'Reserved', 'MISSING | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LAPTOPSTAND', 'Good', 'Lost in Coast'),
    ('eq-0340', 'rigging', 'TRUSS CORNER BOX 1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0341', 'rigging', 'TRUSS CORNER BOX 2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0342', 'rigging', 'TRUSS CORNER BOX 3', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0343', 'rigging', 'TRUSS CORNER BOX 4', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TRUSS', 'Excellent', 'In Store'),
    ('eq-0318', 'rigging', 'TV STAND 1', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TV STAND', 'Good', 'In Store'),
    ('eq-0320', 'rigging', 'TV STAND 2', 1, 'Available', 'Location: In Store', 'N\A', 'N/A', '[]'::jsonb, 'TV STAND', 'Good', 'In Store'),
    ('eq-0696', 'stage', '1M STAGE SKIRTING 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0697', 'stage', '1M STAGE SKIRTING 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0698', 'stage', '1M STAGE SKIRTING 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0699', 'stage', '1M STAGE SKIRTING 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0700', 'stage', '1M STAGE SKIRTING 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0701', 'stage', '1M STAGE SKIRTING 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0702', 'stage', '1M STAGE SKIRTING 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0502', 'stage', '1m by 1m Stage Panel', 1, 'Available', 'Location: In Store', '1m x 1m', 'N\A', '[]'::jsonb, '1m by 1m Stage Platform', 'Excellent', 'In Store'),
    ('eq-0692', 'stage', '2M STAGE SKIRTING 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0693', 'stage', '2M STAGE SKIRTING 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0694', 'stage', '2M STAGE SKIRTING 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0695', 'stage', '2M STAGE SKIRTING 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SKIRTING', 'Excellent', 'In Store'),
    ('eq-0482', 'stage', '2m by 1m Stage Panel', 20, 'Available', '20 panels consolidated. Location: In Store', '2m by 1m', 'N/A', '[]'::jsonb, '2m by 1m Stage Platform', 'Excellent', 'In Store'),
    ('eq-0503', 'stage', 'Adjustable Stage Legs', 78, 'Available', '80 units consolidated (78 available, 2 faulty). Location: In Store', '60cm-93cm', 'N/A', '[]'::jsonb, 'Adjustable Stage Legs', 'Good', 'In Store'),
    ('eq-0751', 'stage', 'PLY WOODS 7PCS', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'PLYWOOD', 'Excellent', 'Lost in Coast'),
    ('eq-0585', 'stage', 'Stage C-Clamps', 41, 'Available', '41 units consolidated. Location: In Store', 'Standard', 'N/A', '[]'::jsonb, 'Stage C-Clamps', 'Excellent', 'In Store'),
    ('eq-0651', 'stage', 'Stage Double Clamps', 12, 'Available', '12 units consolidated. Location: In Store', 'Standard', 'N/A', '[]'::jsonb, 'Stage Double Clamps', 'Excellent', 'In Store'),
    ('eq-0626', 'stage', 'Stage Single Clamps', 18, 'Available', '25 units total: 18 Available (Clamps 1-17, 19), 4 Need Repair (Clamps 20-23), 1 Faulty (Clamp 18), 2 Missing (Clamps 24-25). Location: In Store', 'Standard', 'N/A', '[]'::jsonb, 'Stage Single Clamps', 'Good', 'In Store'),
    ('eq-0583', 'stage', 'Stage Steps', 2, 'Available', '2 units consolidated. Location: In Store', 'Standard', 'N/A', '[]'::jsonb, 'Stage Steps', 'Excellent', 'In Store'),
    ('eq-0663', 'stage', 'Stage Velcro Plates', 29, 'Available', '29 units consolidated. Location: In Store', 'Standard', 'N/A', '[]'::jsonb, 'Stage Velcro Plates', 'Excellent', 'In Store'),
    ('eq-0070', 'visual', '150 W MOVING HEAD 1', 1, 'Available', 'Location: In Store', 'LED SPOT 150', 'D17001588DB37F', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0071', 'visual', '150 W MOVING HEAD 2', 0, 'Reserved', 'Location: Lost in Coast', 'LED SPOT 151', 'D17001338DB366', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0118', 'visual', '230W BEAM FOLLOW SPOT LIHGT', 0, 'Reserved', 'Location: Missing from Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'Missing from Store'),
    ('eq-0286', 'visual', '50M RJ45 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'ETHERNET CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0287', 'visual', '50M RJ45 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'ETHERNET CABLE', 'Excellent', 'Lost in Coast'),
    ('eq-0100', 'visual', 'ACME LED TRI-PAR MP-21TC 1', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110817-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0101', 'visual', 'ACME LED TRI-PAR MP-21TC 2', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110822-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0102', 'visual', 'ACME LED TRI-PAR MP-21TC 3', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110814-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0103', 'visual', 'ACME LED TRI-PAR MP-21TC 4', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110823-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0104', 'visual', 'ACME LED TRI-PAR MP-21TC 5', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110819-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0105', 'visual', 'ACME LED TRI-PAR MP-21TC 6', 1, 'Available', 'Location: In Store', 'MP-21TC D30', 'AE-06110816-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0106', 'visual', 'ACME LED TRI-PAR MP-21TC 7', 1, 'Available', 'Location: In the store', 'MP-21TC D30', 'AE-06110821-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0107', 'visual', 'ACME LED TRI-PAR MP-21TC 8', 1, 'Available', 'Location: In the store', 'MP-21TC D30', 'AE-06110820-A00', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0158', 'visual', 'ACME MARVELED', 0, 'Reserved', 'Location: Missing from Store', 'LED-737', 'AE-08094507-A07', '[]'::jsonb, 'LIGHTS', 'Good', 'Missing from Store'),
    ('eq-0127', 'visual', 'ADJ BEAM MOVING HEAD 1', 1, 'Available', 'Location: In Store', 'VIZI BEAM 5R', '65680322', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0128', 'visual', 'ADJ BEAM MOVING HEAD 2', 1, 'Available', 'lamp needs replacement | Location: In Store', 'VIZI BEAM 5R', '65680324', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0156', 'visual', 'ADJ BLACK LIGHT 1', 0, 'Reserved', 'Location: Lost in Coast', 'ECO UV BAR PLUS IR', '30657049', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0157', 'visual', 'ADJ BLACK LIGHT 2', 0, 'Reserved', 'Location: Lost in Coast', 'ECO UV BAR PLUS IR', '30657440', '[]'::jsonb, 'LIGHTS', 'Good', 'Lost in Coast'),
    ('eq-0124', 'visual', 'ADJ LED DISCO LIGHT', 0, 'Reserved', 'Mic out of place/visual lens replacement | Location: Lost in Coast', 'VERTIGO HEX LED', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0125', 'visual', 'ADJ SPOT MOVING HEAD 1', 1, 'Available', 'Location: In Store', 'INNO POCKET SPOT', '37663160', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0126', 'visual', 'ADJ SPOT MOVING HEAD 2', 1, 'Available', 'Location: In Store', 'INNO POCKET SPOT', '37663159', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0179', 'visual', 'ANTARL SMOKE MACHINE', 1, 'Available', 'Element problem | Location: In the store', 'X-515T', '515E060600088', '[]'::jsonb, 'SMOKE MACHINE', 'Excellent', 'In the store'),
    ('eq-0129', 'visual', 'BEAM 230 MOVING HEAD 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0130', 'visual', 'BEAM 230 MOVING HEAD 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0131', 'visual', 'BEAM 230 MOVING HEAD 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0132', 'visual', 'BEAM 230 MOVING HEAD 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0133', 'visual', 'BEAM 230 MOVING HEAD 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0134', 'visual', 'BEAM 230 MOVING HEAD 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0135', 'visual', 'BEAM 230 MOVING HEAD 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0136', 'visual', 'BEAM 230 MOVING HEAD 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0171', 'visual', 'BEATS BY DRE', 0, 'Broken', 'Shuttered Touch Screen in al nahada sharjah | Location: In Store', 'ALL-IN-ONE PC', 'CZC4311F1B', '[]'::jsonb, 'PC', 'Faulty', 'In Store'),
    ('eq-0162', 'visual', 'BIG DIPPER LASER', 1, 'Available', 'Location: In the house', 'B20000+RGB', 'B220001030', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the house'),
    ('eq-0074', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 1', 1, 'Available', 'Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'In Store'),
    ('eq-0075', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 2', 1, 'Available', 'Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'In Store'),
    ('eq-0076', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 3', 0, 'Broken', 'BROKEN [ICE BRUNT] | Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Faulty', 'In Store'),
    ('eq-0077', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 4', 1, 'Available', 'Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'In Store'),
    ('eq-0078', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 5', 0, 'Broken', 'BROKEN [ICE BRUNT] | Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Faulty', 'In Store'),
    ('eq-0079', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 6', 1, 'Available', 'Location: In Store', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'In Store'),
    ('eq-0080', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 7', 0, 'Reserved', 'Location: Lost in Coast', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'Lost in Coast'),
    ('eq-0081', 'visual', 'BIG DIPPER RGB 3W LED PAR LIGHT 8', 0, 'Reserved', 'Location: Lost in Coast', 'LPC009', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'Lost in Coast'),
    ('eq-0165', 'visual', 'CHAUVET DJ DMX', 0, 'Broken', 'Power cord missing | Location: Needs Reapairs', 'OBEY40', '9080233', '[]'::jsonb, 'DMX', 'Faulty', 'Needs Reapairs'),
    ('eq-0066', 'visual', 'CYCLOPS MOVING HEAD', 4, 'Available', '4 units consolidated. Location: In Store', 'CL-300B-ER', '', '["S020110604084","S020110604062","S020110604061","S020110604076"]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0108', 'visual', 'CYCLOPS PAR LIGHT', 10, 'Available', '10 units consolidated. Location: In Store', 'CPX-418 0P', '', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0763', 'visual', 'DELL LAPTOP', 0, 'Reserved', 'Location: WITH MARIA', 'Latitude 5511', '7SWC793', '[]'::jsonb, 'AUDIO', 'Excellent', 'WITH MARIA'),
    ('eq-0166', 'visual', 'DMX DONGLE 1', 0, 'Reserved', 'Location: Lost in Coast', 'ENTTEC USBDMX PRO', '', '[]'::jsonb, 'DMX', 'Excellent', 'Lost in Coast'),
    ('eq-0167', 'visual', 'DMX DONGLE 2', 0, 'Reserved', 'Location: Lost in Coast', 'CHROMATEQ DMX LPSA 512', 'C11A00G00405', '[]'::jsonb, 'DMX', 'Excellent', 'Lost in Coast'),
    ('eq-0172', 'visual', 'EPSON PROJECTOR', 1, 'Available', 'Location: Stephen', 'EH-TW5300', 'X25V5Y00079', '[]'::jsonb, 'PROJECTOR', 'Excellent', 'Stephen'),
    ('eq-0164', 'visual', 'EUROLITE DMX SUPERSTROBE 2700', 0, 'Reserved', 'Location: Missing from Store', 'DMX SUPERSTROBE 2700', '52202176', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Missing from Store'),
    ('eq-0772', 'visual', 'FAIRY LIGHTS', 1, 'Available', 'Location: in store', 'N/A', 'N/A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'in store'),
    ('eq-0285', 'visual', 'HDMI EXTENDER SET', 0, 'Reserved', 'Location: Lost in Coast', 'GN-AV383', 'N\A', '[]'::jsonb, 'ADAPTER', 'Excellent', 'Lost in Coast'),
    ('eq-0284', 'visual', 'HDMI SPLITTER 1-4', 0, 'Broken', 'BURNED | Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'ADAPTER', 'Faulty', 'Lost in Coast'),
    ('eq-0159', 'visual', 'JELLY FISH', 0, 'Broken', 'FUSE BURNED | Location: Needs Reapairs', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Faulty', 'Needs Reapairs'),
    ('eq-0161', 'visual', 'LASER SHOW SYSTEM', 1, 'Available', 'Location: In Store', 'XHR SD-F1688', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In Store'),
    ('eq-0123', 'visual', 'LED BAR/ DEEJAY BOOTH', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0119', 'visual', 'LED COCKTAIL TABLE 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0120', 'visual', 'LED COCKTAIL TABLE 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0121', 'visual', 'LED COCKTAIL TABLE 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0122', 'visual', 'LED COCKTAIL TABLE 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0168', 'visual', 'LG TV 32" 1', 1, 'Available', 'JOHNNY''S PLACE | Location: In the house', 'LH512U', '608EGCCN3387', '[]'::jsonb, 'TV', 'Excellent', 'In the house'),
    ('eq-0169', 'visual', 'LG TV 32" 2', 1, 'Available', 'JOHNNY''S PLACE | Location: Stephen', 'LH512U', '', '[]'::jsonb, 'TV', 'Excellent', 'Stephen'),
    ('eq-0170', 'visual', 'LG TV 32" 3', 1, 'Available', 'At steves place | Location: Stephen', 'LH512U', '', '[]'::jsonb, 'TV', 'Excellent', 'Stephen'),
    ('eq-0768', 'visual', 'Led screen controller', 1, 'Available', 'Location: In the store', 'X2scolorlight', 'X2s023122409', '[]'::jsonb, 'LED SCREENS', 'Excellent', 'In the store'),
    ('eq-0137', 'visual', 'MOVING PAR LIGHTS  1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0138', 'visual', 'MOVING PAR LIGHTS  2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0139', 'visual', 'MOVING PAR LIGHTS  3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0140', 'visual', 'MOVING PAR LIGHTS  4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0141', 'visual', 'MOVING PAR LIGHTS  5', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0173', 'visual', 'PROJECTOR SCREEN 1 STAND MOUNT (240CM*240CM)', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SCREEN', 'Excellent', 'In Store'),
    ('eq-0174', 'visual', 'PROJECTOR SCREEN 1 WALL MOUNT (240CM*240CM)', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SCREEN', 'Excellent', 'In Store'),
    ('eq-0175', 'visual', 'PROJECTOR SCREEN 1 WALL MOUNT (?CM*?CM)', 1, 'Available', 'At steves place | Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'SCREEN', 'Excellent', 'In Store'),
    ('eq-0082', 'visual', 'RGB 54- 3W LED PAR LIGHT 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'Lost in Coast'),
    ('eq-0083', 'visual', 'RGB 54- 3W LED PAR LIGHT 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'Lost in Coast'),
    ('eq-0098', 'visual', 'RGB 56 3W LED PAR LIGHT 1', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0099', 'visual', 'RGB 56 3W LED PAR LIGHT 2', 0, 'Reserved', 'Location: Lost in Coast', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Lost in Coast'),
    ('eq-0160', 'visual', 'RGB LASER', 0, 'Broken', 'lense missing needs repair | Location: Lost in Coast', 'TVS S-1', 'N\A', '[]'::jsonb, 'LIGHTS', 'Faulty', 'Lost in Coast'),
    ('eq-0084', 'visual', 'RGBW 3W LED PAR LIGHT 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In Store'),
    ('eq-0085', 'visual', 'RGBW 3W LED PAR LIGHT 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In Store'),
    ('eq-0086', 'visual', 'RGBW 3W LED PAR LIGHT 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In Store'),
    ('eq-0087', 'visual', 'RGBW 3W LED PAR LIGHT 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In Store'),
    ('eq-0088', 'visual', 'RGBW 3W LED PAR LIGHT 5', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In the store'),
    ('eq-0089', 'visual', 'RGBW 3W LED PAR LIGHT 6', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Good', 'In the store'),
    ('eq-0090', 'visual', 'RGBWU 3W LED PAR LIGHT 1', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0091', 'visual', 'RGBWU 3W LED PAR LIGHT 2', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0092', 'visual', 'RGBWU 3W LED PAR LIGHT 3', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0093', 'visual', 'RGBWU 3W LED PAR LIGHT 4', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0094', 'visual', 'RGBWU 3W LED PAR LIGHT 5', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0095', 'visual', 'RGBWU 3W LED PAR LIGHT 6', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0096', 'visual', 'RGBWU 3W LED PAR LIGHT 7', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0097', 'visual', 'RGBWU 3W LED PAR LIGHT 8', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0775', 'visual', 'SMALL FAIRY LIGHTS', 1, 'Available', 'Location: in the store', 'N/A', 'N/A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'in the store'),
    ('eq-0176', 'visual', 'SMOKE MACHINE 1', 0, 'Reserved', 'Location: Lost in Coast', 'AB-1800', 'N\A', '[]'::jsonb, 'SMOKE MACHINE', 'Excellent', 'Lost in Coast'),
    ('eq-0177', 'visual', 'SMOKE MACHINE 2', 0, 'Broken', 'HEATER PROBLEM | Location: Needs Reapairs', '2500', 'N\A', '[]'::jsonb, 'SMOKE MACHINE', 'Faulty', 'Needs Reapairs'),
    ('eq-0178', 'visual', 'SMOKE MACHINE 3', 1, 'Available', 'fuse keeps burning | Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'SMOKE MACHINE', 'Excellent', 'In the store'),
    ('eq-0163', 'visual', 'STROBE LIGHT 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Fair', 'In Store'),
    ('eq-0142', 'visual', 'UV BLACK LIGHT 1', 1, 'Available', 'Location: Needs Reapairs', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Needs Reapairs'),
    ('eq-0151', 'visual', 'UV BLACK LIGHT 10', 1, 'Available', 'Location: In the house', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the house'),
    ('eq-0152', 'visual', 'UV BLACK LIGHT 11', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0153', 'visual', 'UV BLACK LIGHT 12', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0154', 'visual', 'UV BLACK LIGHT 13', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0155', 'visual', 'UV BLACK LIGHT 14', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0143', 'visual', 'UV BLACK LIGHT 2', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0144', 'visual', 'UV BLACK LIGHT 3', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0145', 'visual', 'UV BLACK LIGHT 4', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0146', 'visual', 'UV BLACK LIGHT 5', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0147', 'visual', 'UV BLACK LIGHT 6', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0148', 'visual', 'UV BLACK LIGHT 7', 1, 'Available', 'Location: Ina the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'Ina the store'),
    ('eq-0149', 'visual', 'UV BLACK LIGHT 8', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0150', 'visual', 'UV BLACK LIGHT 9', 1, 'Available', 'Location: In the store', 'N\A', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In the store'),
    ('eq-0189', 'visual', 'WEN LED DANCE FLOOR 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0198', 'visual', 'WEN LED DANCE FLOOR 10', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0199', 'visual', 'WEN LED DANCE FLOOR 11', 0, 'Broken', 'button issues | Location: NEEDS REPAIR', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'NEEDS REPAIR'),
    ('eq-0200', 'visual', 'WEN LED DANCE FLOOR 12', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0201', 'visual', 'WEN LED DANCE FLOOR 13', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0202', 'visual', 'WEN LED DANCE FLOOR 14', 0, 'Broken', 'button issues | Location: NEEDS REPAIR', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'NEEDS REPAIR'),
    ('eq-0203', 'visual', 'WEN LED DANCE FLOOR 15', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0204', 'visual', 'WEN LED DANCE FLOOR 16', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0205', 'visual', 'WEN LED DANCE FLOOR 17', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0206', 'visual', 'WEN LED DANCE FLOOR 18', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0207', 'visual', 'WEN LED DANCE FLOOR 19', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0190', 'visual', 'WEN LED DANCE FLOOR 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0208', 'visual', 'WEN LED DANCE FLOOR 20', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0209', 'visual', 'WEN LED DANCE FLOOR 21', 0, 'Broken', 'button issues | Location: NEEDS REPAIR', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'NEEDS REPAIR'),
    ('eq-0210', 'visual', 'WEN LED DANCE FLOOR 22', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0211', 'visual', 'WEN LED DANCE FLOOR 23', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0212', 'visual', 'WEN LED DANCE FLOOR 24', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0213', 'visual', 'WEN LED DANCE FLOOR 25', 1, 'Available', 'Signal cable bruised  (need replacement) | Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Fair', 'In Store'),
    ('eq-0191', 'visual', 'WEN LED DANCE FLOOR 3', 0, 'Broken', 'Location: NEEDS REPAIR', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'NEEDS REPAIR'),
    ('eq-0192', 'visual', 'WEN LED DANCE FLOOR 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0193', 'visual', 'WEN LED DANCE FLOOR 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0194', 'visual', 'WEN LED DANCE FLOOR 6', 0, 'Broken', 'display screen not working | Location: NEEDS REPAIR', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'NEEDS REPAIR'),
    ('eq-0195', 'visual', 'WEN LED DANCE FLOOR 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0196', 'visual', 'WEN LED DANCE FLOOR 8', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0197', 'visual', 'WEN LED DANCE FLOOR 9', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0072', 'visual', 'WEN MOVING HEAD 1', 1, 'Available', 'Location: In Store', 'BEAM 350', 'N\A', '[]'::jsonb, 'LIGHTS', 'Excellent', 'In Store'),
    ('eq-0073', 'visual', 'WEN MOVING HEAD 2', 0, 'Broken', 'bulb needs to be changed | Location: In Store', 'BEAM 350', 'N\A', '[]'::jsonb, 'LIGHTS', 'Faulty', 'In Store'),
    ('eq-0180', 'visual', 'XINGCHEN LED DANCE FLOOR 1', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0181', 'visual', 'XINGCHEN LED DANCE FLOOR 2', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0182', 'visual', 'XINGCHEN LED DANCE FLOOR 3', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0183', 'visual', 'XINGCHEN LED DANCE FLOOR 4', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0184', 'visual', 'XINGCHEN LED DANCE FLOOR 5', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0185', 'visual', 'XINGCHEN LED DANCE FLOOR 6', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0186', 'visual', 'XINGCHEN LED DANCE FLOOR 7', 1, 'Available', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Excellent', 'In Store'),
    ('eq-0187', 'visual', 'XINGCHEN LED DANCE FLOOR 8', 0, 'Broken', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'In Store'),
    ('eq-0188', 'visual', 'XINGCHEN LED DANCE FLOOR 9', 0, 'Broken', 'Location: In Store', 'N\A', 'N\A', '[]'::jsonb, 'LED DANCEFLOOR', 'Faulty', 'In Store')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category_id = EXCLUDED.category_id, available = EXCLUDED.available, status = EXCLUDED.status, notes = EXCLUDED.notes, model = EXCLUDED.model, serial_number = EXCLUDED.serial_number, serials = EXCLUDED.serials, sub_category = EXCLUDED.sub_category, condition = EXCLUDED.condition, location = EXCLUDED.location;

-- 4. EVENTS & PRODUCTIONS
INSERT INTO public.events (id, event_name, client_name, event_date, venue, start_time, end_time, setup_time, breakdown_time, equipment_booked, returned_equipment, notes, assigned_to, status)
VALUES
    ('evt-001', 'Wedding Reception', 'Amina & Daniel', '2026-09-20', 'Nairobi Garden Hotel', '15:00', '22:30', '12:30', '23:00', '2 line array speakers, 1 LED screen, 4 lighting trusses, 1 DJ setup', '', 'Need an elegant lighting setup and strong sound coverage for the main hall.', 'dave', 'Planned'),
    ('evt-002', 'Corporate Launch', 'BluePeak Ltd', '2026-09-25', 'Kenyatta International Convention Centre', '09:00', '13:00', '07:00', '13:30', '1 LED screen, 1 projector, event lighting, sound system', '', 'Company wants a formal stage look with crisp audio and presentation support.', 'mariah', 'Confirmed'),
    ('evt-003', 'Birthday Bash', 'Joyline Muthoni', '2026-09-27', 'Westlands Lounge', '18:00', '23:00', '16:30', '23:30', 'Sound system, LED dance floor, decorative lighting, DJ services', '', 'House playlist and dance floor lighting are key priorities for this event.', 'dave', 'In Progress')
ON CONFLICT (id) DO UPDATE SET event_name = EXCLUDED.event_name, client_name = EXCLUDED.client_name, event_date = EXCLUDED.event_date, venue = EXCLUDED.venue, status = EXCLUDED.status;
